// ==UserScript==
// @name         poe-trade-notable-description
// @version      0.2
// @description  Adds descriptions for the new cluster jewel notables on the official Path of Exile trade site.
// @match        https://www.pathofexile.com/trade/*
// @license      MIT
// ==/UserScript==

(() => {
  const notables = {
    'Prodigious Defence': '3% Chance to Block Spell Damage\n30% increased Attack Damage while holding a Shield\n+3% Chance to Block Attack Damage',
    'Advance Guard': 'Attack Skills deal 30% increased Damage while holding a Shield\nIgnore all Movement Penalties from Armour\n5% increased Movement Speed while holding a Shield',
    'Gladiatorial Combat': '2% increased Attack Damage per 75 Armour or Evasion Rating on Shield\n+1% to Critical Strike Multiplier per 10 Maximum Energy Shield on Shield',
    'Strike Leader': 'Attack Skills deal 30% increased Damage while holding a Shield\n+2% Chance to Block Attack Damage\n+2 to Melee Strike Range while Holding a Shield',
    'Powerful Ward': '20% chance to gain a Power Charge when you Block\n+6% Chance to Block Spell Damage while at Maximum Power Charges',
    'Enduring Ward': '20% chance to gain an Endurance Charge when you Block\n+6% Chance to Block Attack Damage while at Maximum Endurance Charges',
    'Gladiator\'s Fortitude': 'Attack Skills deal 25% increased Damage while holding a Shield\n5% increased maximum Life',
    'Precise Retaliation': '80% increased Critical Strike Chance if you haven’t Blocked Recently\n+40% to Critical Strike Multiplier if you have Blocked Recently',
    'Veteran Defender': '+15 to all Attributes\n+15% Elemental Resistances while holding a Shield\n60% increased Defences from Equipped Shield',
    'Iron Breaker': 'Enemies have -10% to Total Physical Damage Reduction against your Hits\n35% increased Physical Damage',
    'Deep Cuts': '15% chance to Impale Enemies on Hit with Attacks\nImpales you inflict last 1 additional Hit',
    'Master the Fundamentals': '+10% to all Elemental Resistances\n35% reduced Elemental Damage\n35% increased Physical Damage',
    'Force Multiplier': '5% chance to deal Double Damage\n25% increased Physical Damage',
    'Furious Assault': '8% increased Attack and Cast Speed\n25% increased Physical Damage',
    'Vicious Skewering': 'Attacks have 10% chance to cause Bleeding\n10% chance to Impale Enemies on Hit with Attacks\n15% increased Effect of Impales inflicted by Hits that also inflict Bleeding',
    'Grim Oath': 'Gain 10% of Physical Damage as Extra Chaos Damage',
    'Battle-Hardened': '30% increased Evasion Rating and Armour\n35% increased Physical Damage',
    'Replenishing Presence': '8% increased effect of Non-Curse Auras from your Skills\nAuras from your Skills grant 0.2% of Life Regenerated per second to\nyou and Allies',
    'Master of Command': '50% reduced Mana Reservation of Banner Skills\n15% increased Effect of Non-Curse Auras from your Skills on Enemies',
    'First Among Equals': '10% increased effect of Non-Curse Auras from your Skills\nNon-Curse Aura Skills have 20% increased Duration',
    'Purposeful Harbinger': '10% increased Effect of Auras on You for each Herald affecting you',
    'Precise Commander': 'You and nearby Allies have 50% increased Critical Strike Chance\nYou and nearby Allies have +15% to Critical Strike Multiplier',
    'Pure Commander': 'Purity of Elements has 30% increased Aura Effect\nPurity of Fire has 30% increased Aura Effect\nPurity of Ice has 30% increased Aura Effect\nPurity of Lightning has 30% increased Aura Effect',
    'Stalwart Commander': 'Grace has 30% increased Aura Effect\nDetermination has 30% increased Aura Effect\nDiscipline has 30% increased Aura Effect',
    'Vengeful Commander': 'Anger has 30% increased Aura Effect\nWrath has 30% increased Aura Effect\nHatred has 30% increased Aura Effect',
    'Skullbreaker': '8% reduced Enemy Stun Threshold\n+20% to Critical Strike Multiplier',
    'Pressure Points': 'Your Critical Strikes have a 5% chance to deal Double Damage\n40% increased Critical Strike Chance',
    'Overwhelming Malice': '10% chance to gain Unholy Might for 4 seconds on Critical Strike',
    'Magnifier': '10% increased Area of Effect\n10% increased Area Damage\n+10% to Critical Strike Multiplier',
    'Savage Response': '+50% to Critical Strike Multiplier if you\'ve taken a Savage Hit Recently\n40% increased Critical Strike Chance',
    'Eye of the Storm': '+20% to Damage over Time Multiplier for Ignite from Critical Strikes\n20% increased Effect of Chill you inflict with Critical Strikes\n20% increased Effect of Shock you inflict with Critical Strikes\n40% increased Critical Strike Chance',
    'Basics of Pain': '20% increased Damage\n30% increased Critical Strike Chance',
    'Quick Getaway': '5% increased Attack and Cast Speed\n5% increased Movement Speed if you\'ve dealt a Critical Strike Recently\n25% increased Critical Strike Chance',
    'Assert Dominance': '10% increased Area Damage\n15% increased Area of Effect if you\'ve Killed Recently\n10% increased Area of Effect if you\'ve Killed at least 5 Enemies Recently',
    'Vast Power': '20% increased Area Damage\n3% increased Area of Effect per Power Charge',
    'Powerful Assault': '20% increased Area Damage\nArea Skills have 10% chance to Knock Enemies Back on Hit',
    'Intensity': '10% increased Area Damage\nSkills supported by Intensify have +1 to maximum Intensity',
    'Titanic Swings': '20% increased Area Damage while wielding a Two Handed Melee Weapon\n15% increased Area of Effect while wielding a Two Handed Melee Weapon',
    'Towering Threat': '5% increased maximum Life\n10% increased Area of Effect\n3% increased Character Size',
    'Ancestral Echo': '20% increased Totem Placement speed\n10% increased Attack and Cast Speed if you\'ve summoned a Totem Recently',
    'Ancestral Reach': '25% increased Totem Damage\n25% increased Totem Placement speed\n25% increased Totem Placement range',
    'Ancestral Might': '20% increased Totem Damage\n30% increased Totem Duration\n30% increased Totem Damage if you haven\'t Summoned a Totem in the past 2 seconds',
    'Ancestral Preservation': '30% increased Totem Life\nTotems have 10% additional Physical Damage Reduction\nTotems gain +40% to Chaos Resistance',
    'Snaring Spirits': '30% increased Totem Damage\nTotems Hinder Enemies near them when Summoned, with 25% reduced Movement Speed',
    'Sleepless Sentries': '20% increased Totem Damage\n20% increased Totem Duration\nAttack Skills have +1 to maximum number of Summoned Ballista Totems',
    'Ancestral Guidance': '30% increased Effect of Buffs granted by your Active Ancestor Totems\nTotems\' Action Speed cannot be modified to below base value',
    'Ancestral Inspiration': 'Gain Arcane Surge when you Summon a Totem\nSpells cast by Totems deal 25% increased Damage',
    'Vital Focus': 'Channelling Skills deal 30% increased Damage\nRegenerate 1.5% of Life per second while Channelling',
    'Rapid Infusion': '50% increased Effect of Infusion\n5% increased Movement Speed while you have Infusion',
    'Unwavering Focus': '40% chance to Avoid being Stunned while Channelling\nChannelling Skills deal 25% increased Damage\n15% reduced Mana Cost of Channelling Skills',
    'Enduring Focus': 'Channelling Skills deal 25% increased Damage\n25% chance to gain an Endurance Charge each second while Channelling',
    'Precise Focus': '50% increased Critical Strike Chance while Channelling\n+30% to Critical Strike Multiplier if you\'ve been Channelling for at least 1 second',
    'Stoic Focus': '+4% Chance to Block Attack Damage while Channelling\n+4% Chance to Block Spell Damage while Channelling\nChannelling Skills deal 25% increased Damage',
    'Hex Breaker': '8% increased Attack and Cast Speed while Channelling\nImmune to Curses while Channelling',
    'Arcane Adept': '5% increased Attack and Cast Speed while Channelling\nChannelling Skills deal 20% increased Damage\nGain Arcane Surge after Channelling for 1 second',
    'Distilled Perfection': '25% increased Life Recovery from Flasks\n25% increased Mana Recovery from Flasks\n20% increased Flask Effect Duration',
    'Spiked Concoction': 'Flasks applied to you have 10% increased Effect\n5% increased Attack and Cast Speed during any Flask Effect',
    'Fasting': '20% increased Flask Charges gained\n20% increased Movement Speed while under no Flask Effects',
    'Mender\'s Wellspring': '25% increased Life Recovery from Flasks\nLife Flasks gain 1 Charge every 3 seconds\nRemove Bleeding when you use a Life Flask',
    'Special Reserve': '20% increased Damage during any Flask Effect\nRegenerate 2% of Life per second during any Flask Effect',
    'Numbing Elixir': '25% increased Life Recovery from Flasks\n25% increased Mana Recovery from Flasks\n3% additional Physical Damage Reduction during Effect of any Life or Mana Flask',
    'Mob Mentality': '20% increased Warcry Cooldown Recovery Speed\nYou and nearby Party members gain 5 Rage when you Warcry',
    'Cry Wolf': '30% increased Warcry Duration\nWarcries count as having 10 additional nearby Enemies\n30% increased Warcry Buff Effect',
    'Haunting Shout': '20% increased Warcry Cooldown Recovery Speed\nEnemies Taunted by your Warcries are Intimidated\nEnemies Taunted by your Warcries are Unnerved',
    'Lead By Example': '4% additional Physical Damage Reduction if you\'ve Warcried in the past 8 seconds\n4% chance to deal Double Damage if you\'ve Warcried in the past 8 seconds',
    'Provocateur': '40% increased Critical Strike Chance against Taunted Enemies\n+15% to Critical Strike Multiplier against Taunted Enemies\n15% increased Warcry Buff Effect',
    'Warning Call': '20% increased Warcry Cooldown Recovery Speed\n50% increased Melee Critical Strike Chance if you\'ve Warcried Recently\n+35% to Melee Critical Strike Multiplier if you\'ve Warcried Recently',
    'Rattling Bellow': 'Enemies Taunted by you take 5% increased Damage\nWarcry Skills have 40% increased Area of Effect',
    'Bloodscent': 'Attacks with Axes or Swords grant 1 Rage on Hit, no more than once every second',
    'Run Through': 'Axe or Sword Attacks deal 15% increased Damage with Ailments\n10% increased Impale Effect\n10% chance to Impale Enemies on Hit with Axes or Swords\n15% increased Physical Damage with Axes or Swords',
    'Wound Aggravation': 'Axe or Sword Attacks deal 20% increased Damage with Ailments\n20% increased Physical Damage with Axes or Swords\n+10% to Physical Damage over Time Multiplier while wielding an Axe or Sword',
    'Overlord': '30% increased Damage with Maces, Sceptres or Staves\nGain Fortify for 6 seconds on Melee Hit with a Mace, Sceptre or Staff',
    'Expansive Might': 'Mace, Sceptre or Staff Attacks deal 20% increased Damage with Hits and Ailments\nWhile stationary, gain 10% increased Area of Effect every second, up to a maximum of 50%',
    'Weight Advantage': 'Mace, Sceptre or Staff Attacks deal 30% increased Damage with Hits and Ailments\n4% chance to deal Double Damage while wielding a Mace, Sceptre or Staff\n+20 to Strength',
    'Wind-up': '+15% to Critical Strike Multiplier with Claws or Daggers\n10% chance to gain a Power Charge on Non-Critical Strike with a Claw or Dagger',
    'Fan of Blades': 'Attack Skills fire an additional Projectile while wielding a Claw or Dagger\n20% increased Projectile Attack Damage with Claws or Daggers',
    'Disease Vector': 'Enemies Poisoned by you cannot Regenerate Life\n+10% to Damage over Time Multiplier for Poison while wielding a Claw or Dagger',
    'Arcing Shot': 'Arrows gain Critical Strike Chance as they travel farther, up to 100% increased Critical Strike Chance\nArrows gain Damage as they travel farther, dealing up to 50% increased Damage with Hits to targets',
    'Tempered Arrowheads': 'Bow Skills have +10% to Damage over Time Multiplier\nBow Skills have 20% increased Skill Effect Duration\n10% increased Duration of Ailments inflicted while wielding a Bow',
    'Broadside': 'Bow Skills have 25% increased Area of Effect',
    'Explosive Force': 'Enemies killed by your Wand Hits have a 10% chance to Explode, dealing a quarter of their Life as Chaos Damage\nGain 10% of Wand Physical Damage as Extra Chaos Damage',
    'Opportunistic Fusilade': '50% increased Critical Strike Chance with Wands\n35% increased Damage with Wands if you\'ve dealt a Critical Strike Recently',
    'Storm\'s Hand': 'Gain 10% of Wand Physical Damage as Extra Lightning Damage\n25% of Wand Physical Damage converted to Lightning Damage',
    'Battlefield Dominator': 'Attacks with Two Handed Weapons deal 25% increased Damage with Hits and Ailments\n10% reduced Enemy Stun Threshold\n15% increased Area of Effect if you\'ve Stunned an Enemy with a Two Handed Melee Weapon Recently',
    'Martial Mastery': '10% increased Attack Speed with Two Handed Melee Weapons\n10% increased Attack Speed if you have at least 600 Strength\n+20 to Strength',
    'Surefooted Striker': '40% increased Critical Strike Chance with Two Handed Melee Weapons\n8% chance to deal Double Damage if you\'ve dealt a Critical Strike with a Two Handed Melee Weapon Recently',
    'Graceful Execution': '5% increased Attack Speed with Two Handed Melee Weapons\n15% increased Accuracy Rating with Two Handed Melee Weapons\n25% increased Critical Strike Chance with Two Handed Melee Weapons\n+15 to Dexterity and Intelligence',
    'Brutal Infamy': '40% increased Damage with Hits and Ailments against Unique Enemies',
    'Fearsome Warrior': '8% increased Area of Effect\n25% chance to Intimidate nearby Enemies for 4 seconds on Melee Kill',
    'Combat Rhythm': '10% increased Attack Speed if you\'ve Hit with your Main Hand Weapon Recently\n10% increased Movement Speed if you\'ve Hit with your Off Hand Weapon Recently',
    'Hit and Run': 'Attack Skills deal 20% increased Damage while Dual Wielding\n4% chance to Dodge Attack or Spell Hits if you\'ve Hit an Enemy Recently',
    'Insatiable Killer': 'Attack Skills deal 20% increased Damage while Dual Wielding\n5% increased Attack Speed while Dual Wielding\n5% chance to gain a Frenzy Charge on Kill while Dual Wielding',
    'Mage Bane': '+5% Chance to Block Spell Damage while Dual Wielding\nAttack Skills deal 20% increased Damage while Dual Wielding\n20% chance to gain a Power Charge when you Block',
    'Martial Momentum': '8% increased Attack Speed while Dual Wielding\n16% increased Accuracy Rating while Dual Wielding\n32% increased Damage if you\'ve used a Travel Skill Recently',
    'Deadly Repartee': '+5% Chance to Block Attack Damage while Dual Wielding\nAttack Skills deal 25% increased Damage while Dual Wielding\n30% increased Attack Critical Strike Chance while Dual Wielding',
    'Quick and Deadly': '60% increased Main Hand Attack Damage while wielding two different Weapon Types\n30% increased Off Hand Attack Speed while wielding two different Weapon Types',
    'Smite the Weak': '40% increased Attack Damage against Maimed Enemies\nAttacks have 10% chance to Maim on Hit',
    'Heavy Hitter': '30% increased Attack Damage\n10% reduced Enemy Stun Threshold\n20% chance to double Stun Duration\n30% increased Damage with Ailments from Attack Skills',
    'Martial Prowess': '20% increased Attack Damage\n6% increased Attack Speed\n15% increased Global Accuracy Rating\n20% increased Damage with Ailments from Attack Skills',
    'Calamitous': '10% chance to Freeze, Shock and Ignite\n30% increased Elemental Damage with Attack Skills\n15% increased Effect of Non-Damaging Ailments',
    'Devastator': '20% increased Attack Damage\n20% increased Damage with Ailments from Attack Skills\nEnemies killed by your Attack Hits have a 15% chance to Explode, dealing a tenth of their maximum Life as Physical Damage',
    'Fuel the Fight': '8% increased Attack Speed\n0.4% of Attack Damage Leeched as Mana\n20% increased Damage while Leeching',
    'Drive the Destruction': '0.8% of Attack Damage Leeched as Life\n20% increased Maximum total Recovery per second from Life Leech\n20% increased total Recovery per second from Life Leech',
    'Feed the Fury': '0.4% of Attack Damage Leeched as Life\n30% increased Damage while Leeching\n15% increased Attack Speed while Leeching',
    'Seal Mender': 'Skills Supported by Unleash have 30% increased Seal gain frequency',
    'Conjured Wall': '25% increased Spell Damage\n+6% Chance to Block Spell Damage if you\'ve Cast a Spell Recently',
    'Arcane Heroism': '30% increased Effect of Arcane Surge on you\n10% chance to gain Arcane Surge when you Hit a Unique enemy',
    'Practiced Caster': '20% increased Spell Damage\n5% increased Cast Speed\n35% chance to Avoid interruption from Stuns while Casting',
    'Burden Projection': '30% increased Spell Damage\n8% chance to Knock Enemies Back on Hit with Spell Damage',
    'Thaumophage': '0.6% of Spell Damage Leeched as Energy Shield\n20% increased Maximum total Recovery per second from Energy Shield Leech\n10% chance to Hinder Enemies on Hit with Spells, with 30% reduced Movement Speed',
    'Essence Rush': '40% increased Damage while Leeching Energy Shield\n0.3% of Spell Damage Leeched as Energy Shield\n5% increased Attack and Cast Speed while Leeching Energy Shield',
    'Sap Psyche': '20% increased Spell Damage\n30% increased Mana Regeneration Rate\nRegenerate 1% of Energy Shield per second if you’ve Cursed an Enemy Recently',
    'Sadist': '15% increased Elemental Damage if you\'ve Chilled an Enemy Recently\n20% increased Elemental Damage if you\'ve Ignited an Enemy Recently\n25% increased Elemental Damage if you\'ve Shocked an Enemy Recently',
    'Corrosive Elements': '15% increased Elemental Damage\nCold Skills have a 25% chance to apply Cold Exposure on Hit\nFire Skills have a 25% chance to apply Fire Exposure on Hit\nLightning Skills have a 25% chance to apply Lightning Exposure on Hit',
    'Doryani\'s Lesson': '0.2% of Elemental Damage Leeched as Life\n25% increased Elemental Damage',
    'Disorienting Display': '25% increased Elemental Damage\n10% chance to Blind nearby Enemies when you use an Elemental Skill',
    'Prismatic Heart': '+10% to all Elemental Resistances\n30% increased Elemental Damage',
    'Widespread Destruction': '10% increased Area of Effect\n20% increased Elemental Damage',
    'Master of Fire': 'Nearby Enemies have Fire Exposure',
    'Smoking Remains': '35% increased Fire Damage\n10% chance to create a Smoke Cloud on Kill',
    'Cremator': '30% increased Fire Damage\nIgnited Enemies you hit are destroyed on Kill',
    'Snowstorm': 'Gain 10% of Lightning Damage as Extra Cold Damage against Chilled Enemies',
    'Storm Drinker': 'Damage Penetrates 8% Lightning Resistance\n0.5% of Lightning Damage Leeched as Energy Shield',
    'Paralysis': '30% increased Lightning Damage\n10% chance to double Stun Duration\nLightning Skills have 10% reduced Enemy Stun Threshold',
    'Supercharge': 'Lightning Damage with Non-Critical Strikes is Lucky',
    'Blanketed Snow': 'Damage Penetrates 10% Cold Resistance against Chilled Enemies',
    'Cold to the Core': '1% increased Cold Damage per 25 Dexterity\n1% increased Cold Damage per 25 Intelligence\n1% increased Cold Damage per 25 Strength',
    'Cold-Blooded Killer': '20% increased Cold Damage\nRecover 2% of Life on Kill',
    'Touch of Cruelty': 'Chaos Skills have 10% chance to Hinder Enemies on Hit, with 30% reduced Movement Speed\nEnemies Hindered by you take 10% increased Chaos Damage',
    'Unwaveringly Evil': '30% increased Chaos Damage\nChaos Skills ignore interruption from Stuns',
    'Unspeakable Gifts': 'Enemies you Kill have a 10% chance to Explode, dealing a quarter of their maximum Life as Chaos Damage',
    'Dark Ideation': '2% increased Chaos Damage per 100 maximum Mana, up to a maximum of 80%',
    'Unholy Grace': '30% increased Chaos Damage\n10% increased Attack and Cast Speed',
    'Wicked Pall': '35% increased Chaos Damage\n20% increased Skill Effect Duration',
    'Renewal': 'Minions Regenerate 1% of Life per second\nMinions have 10% chance to deal Double Damage while they are on Full Life',
    'Raze and Pillage': 'Minions have 20% chance to Ignite\nMinions deal 20% increased Damage against Ignited Enemies\nMinions gain 6% of Physical Damage as Extra Fire Damage',
    'Rotten Claws': 'Minions have a 20% chance to Impale on Hit with Attacks',
    'Call to the Slaughter': 'Minions deal 15% increased Damage\nMinions created Recently have 10% increased Attack and Cast Speed\nMinions created Recently have 30% increased Movement Speed',
    'Skeletal Atrophy': 'Summoned Skeletons have 10% chance to Wither Enemies for 2 seconds on Hit\nSummoned Skeletons have 30% of Physical Damage Converted to Chaos Damage',
    'Hulking Corpses': 'Minions have 20% increased maximum Life\n20% increased Raised Zombie Size\nRaised Zombies have 5% chance to Taunt Enemies on Hit',
    'Vicious Bite': 'Minions have 50% increased Critical Strike Chance\nRaised Spectres, Raised Zombies, and Summoned Skeletons have +50% to Critical Strike Multiplier',
    'Primordial Bond': '10% increased Damage per Summoned Golem\n40% increased Effect of Buffs granted by your Golems\nGolems have 25% increased Maximum Life',
    'Blowback': 'Ignites you inflict deal Damage 15% faster',
    'Fan the Flames': 'Ignites you inflict spread to other Enemies within a Radius of 15',
    'Cooked Alive': '15% chance to Ignite\nEnemies Ignited by you have -10% to Fire Resistance',
    'Burning Bright': '+8% to Fire Damage over Time Multiplier\n20% increased Fire Damage\n8% increased Area of Effect',
    'Wrapped in Flame': '20% increased Burning Damage\n+15% to Fire Damage over Time Multiplier while Burning\nRegenerate 1.50% of Life per second while Burning',
    'Vivid Hues': '+12% to Damage over Time Multiplier for Bleeding\n2% of Attack Damage Leeched as Life against Bleeding Enemies\n20% increased total Recovery per second from Life Leech',
    'Rend': '+12% to Damage over Time Multiplier for Bleeding\n30% increased Bleeding Duration',
    'Disorienting Wounds': '25% increased Damage with Bleeding\n25% chance to Blind with Hits against Bleeding Enemies',
    'Compound Injury': '50% increased Damage with Bleeding you inflict on Maimed Enemies',
    'Septic Spells': '8% increased Cast Speed\nSpell Skills have +10% to Damage over Time Multiplier for Poison\n20% chance to Poison on Hit with Spell Damage',
    'Low Tolerance': '+8% to Damage over Time Multiplier for Poison\nPoisons you inflict on non-Poisoned Enemies deal 300% increased Damage',
    'Steady Torment': '20% increased Poison Duration\n20% increased Bleeding Duration\n+10% to Damage over Time Multiplier for Bleeding you inflict on Poisoned Enemies\n+10% to Damage over Time Multiplier for Poison you inflict on Bleeding Enemies',
    'Eternal Suffering': '+5% to Chaos Damage over Time Multiplier\nChaos Skills have 30% increased Skill Effect Duration',
    'Eldritch Inspiration': '+8% to Chaos Damage over Time Multiplier\n16% increased maximum Mana\n20% increased Mana Regeneration Rate',
    'Wasting Affliction': '20% increased Damage with Ailments\nDamaging Ailments deal damage 10% faster',
    'Haemorrhage': '+18% to Damage over Time Multiplier for Ailments from Critical Strikes\n40% increased Critical Strike Chance',
    'Flow of Life': '24% increased Damage over Time\n4% increased maximum Life\nRegenerate 0.6% of Life per second',
    'Exposure Therapy': '+10% to Damage over Time Multiplier\n+30% Chaos Resistance against Damage Over Time',
    'Brush with Death': '+10% to Damage over Time Multiplier\nRecover 1% of Life on Kill\nRecover 1% of Energy Shield on Kill',
    'Vile Reinvigoration': '24% increased Damage over Time\n6% increased maximum Energy Shield\nRegenerate 2% of Energy Shield per second if you’ve Killed an Enemy Recently',
    'Circling Oblivion': '20% increased Damage over Time\n20% increased Duration of Ailments on Enemies\n15% increased Skill Effect Duration',
    'Brewed for Potency': '24% increased Damage over Time\n10% increased Flask Charges gained\n20% increased Life and Mana Recovery from Flasks',
    'Astonishing Affliction': '20% increased Duration of Elemental Ailments on Enemies\n20% increased Damage with Hits and Ailments against Enemies affected by Ailments\n20% increased Effect of Non-Damaging Ailments',
    'Cold Conduction': 'Enemies Chilled by your Hits are Shocked\nEnemies Shocked by your Hits are Chilled',
    'Inspired Oppression': '20% increased Elemental Damage\n30% increased Mana Regeneration Rate if you have Frozen an Enemy Recently\n30% increased Mana Regeneration Rate if you have Shocked an Enemy Recently\n10% increased Effect of Non-Damaging Ailments',
    'Chilling Presence': 'Nearby Enemies are Chilled',
    'Deep Chill': '+10% to Cold Damage over Time Multiplier\n30% increased Effect of Chill',
    'Blast-Freeze': '20% increased Cold Damage\nFreezes you inflict spread to other Enemies within a Radius of 12',
    'Thunderstruck': '20% increased Lightning Damage\nYour Critical Strikes Knock Back Shocked Enemies\n30% increased Critical Strike Chance',
    'Stormrider': '10% chance to gain a Power Charge when you Shock a Chilled Enemy\n25% increased Cold Damage with Hits against Shocked Enemies\n25% increased Lightning Damage with Hits against Chilled Enemies',
    'Overshock': '30% increased Lightning Damage\nYour Shocks can increase Damage taken by up to a maximum of 60%\n30% increased Effect of Shock',
    'Evil Eye': 'Enemies you Curse take 5% increased Damage\n5% chance to Dodge Attack Hits from Cursed Enemies',
    'Whispers of Death': '5% increased Effect of your Curses\n20% increased Damage if you\'ve Killed a Cursed Enemy Recently',
    'Forbidden Words': '25% increased Area of Effect of Curse Skills\n5% increased Effect of your Curses\nCurse Skills have 5% reduced Mana Reservation',
    'Dark Discourse': '10% increased Effect of your Curses\nEnemies you Curse are Hindered, with 15% reduced Movement Speed\nRegenerate 1% of Energy Shield per second if you’ve Killed an Enemy Recently',
    'Victim Maker': 'Curse Skills have 50% increased Skill Effect Duration\n25% increased Damage with Hits and Ailments against Cursed Enemies',
    'Master of Fear': 'Enemies you Curse are Intimidated\nEnemies you Curse are Unnerved',
    'Wish for Death': 'You have Culling Strike against Cursed Enemies\nCurse Skills have 20% increased Skill Effect Duration',
    'Heraldry': '20% increased Effect of Herald Buffs on you\n10% reduced Mana Reservation of Herald Skills',
    'Endbringer': '25% increased Damage for each Herald affecting you',
    'Cult-Leader': 'Minions deal 35% increased Damage while you are affected by a Herald',
    'Empowered Envoy': 'Herald Skills deal 40% increased Damage\n20% increased Effect of Herald Buffs on you',
    'Dark Messenger': 'Herald Skills have 25% increased Area of Effect\nHerald Skills deal 20% increased Damage',
    'Agent of Destruction': '10% chance to Freeze, Shock and Ignite while affected by a Herald\n25% increased Elemental Damage while affected by a Herald',
    'Lasting Impression': '30% increased Damage over Time while affected by a Herald\nHerald Skills deal 50% increased Damage over Time',
    'Self-Fulfilling Prophecy': '+1% to Critical Strike Chance of Herald Skills\n+25% to Critical Strike Multiplier if you dealt a Critical Strike with a Herald Skill Recently',
    'Invigorating Portents': 'Minions deal 20% increased Damage while you are affected by a Herald\nMinions have 10% increased Movement Speed for each Herald affecting you',
    'Pure Agony': '+1 to maximum number of Sentinels of Purity\n+5 to Maximum Virulence\nMinions deal 20% increased Damage while you are affected by a Herald',
    'Disciples': '1% additional Physical Damage Reduction per Summoned Sentinel of Purity\nYou lose Virulence 30% slower\nMinions deal 20% increased Damage while you are affected by a Herald',
    'Dread March': 'Minions have 10% increased maximum Life\nMinions have 10% increased Movement Speed\nMinions have 10% additional Physical Damage Reduction\nMinions have +10% to Chaos Resistance',
    'Blessed Rebirth': 'Minions have 20% increased maximum Life\nMinions created Recently cannot be Damaged',
    'Life from Death': 'Minions have 15% increased maximum Life\nRegenerate 2% of Life per second if a Minion has Died Recently\nMinions Recover 4% of Life on Minion Death',
    'Feasting Fiends': 'Minions have 10% increased maximum Life\nMinions deal 10% increased Damage\nMinions Leech 0.4% of Damage as Life',
    'Bodyguards': 'Minions have 10% increased maximum Life\nMinions have 10% chance to Knock Enemies Back on Hit with Attacks',
    'Follow-Through': 'Projectiles deal 15% increased Damage for each remaining Chain',
    'Streamlined': '30% increased Projectile Speed\n20% increased Projectile Damage',
    'Shrieking Bolts': '35% increased Projectile Damage\n10% chance to Taunt Enemies on Projectile Hit',
    'Eye to Eye': '25% increased Projectile Damage\n35% increased Projectile Damage with Hits against Nearby Enemies',
    'Repeater': '30% increased Projectile Damage\n8% increased Attack and Cast Speed',
    'Aerodynamics': 'Projectiles Pierce an additional Target\n20% increased Projectile Speed\n10% increased Projectile Damage',
    'Chip Away': '25% increased Brand Activation Frequency if you haven\'t used a Brand Skill Recently\n20% increased Brand Attachment range',
    'Seeker Runes': '25% increased Damage with Brand Skills\nUnattached Brands gain 20% increased Brand Attachment Range per second',
    'Remarkable': 'You can Cast an additional Brand\n12% increased Cast Speed with Brand Skills',
    'Brand Loyalty': 'Enemies take 5% increased Damage for each of your Brands Attached to them\n20% increased Brand Attachment range',
    'Holy Conquest': '5% increased Movement Speed\n20% increased Damage with Brand Skills\n10% increased Brand Activation frequency',
    'Grand Design': 'You can Cast an additional Brand\nBrand Skills have 20% increased Duration\n10% increased Brand Activation frequency\n20% increased Brand Attachment range',
    'Set and Forget': '25% increased Trap Damage\n12% increased Area of Effect\n25% reduced Trap Duration\n40% increased Trap Trigger Area of Effect',
    'Expert Sabotage': '30% increased Mine Damage\nCan have up to 2 additional Remote Mines placed at a time\nMines have 20% increased Detonation Speed',
    'Guerilla Tactics': '20% increased Trap Damage\n20% increased Mine Damage\n10% increased Trap Throwing Speed\n10% increased Mine Throwing Speed\n5% increased Movement Speed if you\'ve thrown a Trap or Mine Recently',
    'Expendability': '10% chance to throw up to 1 additional Trap or Mine',
    'Arcane Pyrotechnics': '20% increased Trap Damage\n20% increased Mine Damage\nGain Arcane Surge when your Mine is Detonated targeting an Enemy\nGain Arcane Surge when your Trap is Triggered by an Enemy',
    'Surprise Sabotage': '+15% to Critical Strike Multiplier with Traps\n+15% to Critical Strike Multiplier with Mines\nTrap Damage Penetrates 5% Elemental Resistances\nMine Damage Penetrates 5% Elemental Resistances',
    'Careful Handling': '15% increased Trap Damage\n15% increased Mine Damage\n4% increased maximum Life\n6% increased maximum Mana',
    'Peak Vigour': '8% increased maximum Life\n30% increased Life Recovery from Flasks',
    'Fettle': '+20 to maximum Life\n10% increased maximum Life',
    'Feast of Flesh': '8% increased maximum Life\n0.4% of Attack Damage Leeched as Life\n+10 Life gained for each Enemy hit by your Attacks',
    'Sublime Sensation': '10% increased maximum Energy Shield\n8% increased maximum Life',
    'Surging Vitality': '8% increased maximum Life\nRegenerate 0.5% of Life per second\nEvery 5 seconds, Regenerate 10% of Life over one second',
    'Peace Amidst Chaos': '8% increased maximum Life\n2% additional Physical Damage Reduction while stationary\nRegenerate 2% of Life per second while stationary',
    'Adrenaline': '6% increased maximum Life\n15% increased Maximum total Recovery per second from Life Leech\n6% increased Attack Speed while Leeching',
    'Wall of Muscle': '6% increased maximum Life\n5% increased Strength',
    'Mindfulness': '15% increased maximum Mana\n80% increased Mana Regeneration Rate while stationary',
    'Liquid Inspiration': '15% increased maximum Mana\n30% increased Mana Recovery from Flasks\n5% increased Mana Recovery Rate during Effect of any Mana Flask',
    'Openness': '+30 to maximum Mana\n20% increased maximum Mana',
    'Daring Ideas': '18% increased maximum Mana\n0.4% of Attack Damage Leeched as Mana',
    'Clarity of Purpose': '15% increased maximum Mana\n30% increased Mana Regeneration Rate',
    'Scintillating Idea': '20% increased maximum Mana\nDamage Penetrates 5% Lightning Resistance',
    'Holistic Health': '8% increased maximum Life\n10% increased maximum Mana',
    'Genius': '8% increased maximum Mana\n5% increased Intelligence',
    'Improvisor': '6% increased Attack Speed\n10% increased maximum Mana\n+3 Mana gained for each Enemy hit by your Attacks',
    'Stubborn Student': '20% increased Armour\n15% increased maximum Mana\n4% additional Physical Damage Reduction',
    'Savour the Moment': '10% increased maximum Energy Shield\nRegenerate 3.00% of Energy Shield per second while stationary',
    'Energy From Naught': '+100 to maximum Energy Shield',
    'Will Shaper': 'Gain 5% of Maximum Mana as Extra Maximum Energy Shield',
    'Spring Back': '6% increased maximum Energy Shield\n10% faster start of Energy Shield Recharge\n15% increased Energy Shield Recharge Rate',
    'Conservation of Energy': '8% increased maximum Energy Shield\n0.3% of Spell Damage Leeched as Energy Shield\n20% increased Maximum total Recovery per second from Energy Shield Leech',
    'Heart of Iron': 'Gain 10% of Maximum Life as Extra Armour',
    'Prismatic Carapace': '30% increased Armour\n+1% to all maximum Elemental Resistances',
    'Militarism': '30% increased Armour\n8% increased maximum Life',
    'Second Skin': '3% Chance to Block Spell Damage\n30% increased Armour\n+3% Chance to Block Attack Damage',
    'Dragon Hunter': '30% increased Armour\n+20% to Fire Resistance\n5% additional Physical Damage Reduction',
    'Enduring Composure': '30% increased Armour\nGain an Endurance Charge every second if you\'ve been Hit Recently',
    'Prismatic Dance': '30% increased Evasion Rating\n+1% to all maximum Elemental Resistances',
    'Natural Vigour': '30% increased Evasion Rating\n8% increased maximum Life',
    'Untouchable': '30% increased Evasion Rating\n3% chance to Dodge Attack Hits\n3% chance to Dodge Spell Hits',
    'Shifting Shadow': '20% increased Evasion Rating\n+20 to Dexterity\n10% chance to Blind Enemies on Hit',
    'Readiness': '+4% chance to Evade Attack Hits if you haven\'t been Hit Recently',
    'Confident Combatant': '1% increased Damage per 1% Chance to Block Attack Damage',
    'Flexible Sentry': '3% Chance to Block Spell Damage\n25% chance to Avoid Elemental Ailments\n+3% Chance to Block Attack Damage',
    'Vicious Guard': '0.4% of Attack Damage Leeched as Life\nRegenerate 1.5% of Life per second\n+4% Chance to Block Attack Damage',
    'Mystical Ward': '4% Chance to Block Spell Damage\n0.3% of Spell Damage Leeched as Energy Shield\nRegenerate 1.5% of Energy Shield per second',
    'Rote Reinforcement': '+20 to maximum Life\n20% chance to gain an Endurance Charge when you Block\n+4% Chance to Block Attack Damage',
    'Mage Hunter': '4% Chance to Block Spell Damage\n20% increased Spell Damage\n20% chance to gain a Power Charge when you Block',
    'Riot Queller': '+4% Chance to Block Attack Damage\nEnemies Taunted by you take 6% increased Damage',
    'One with the Shield': 'Recover 50 Life when you Block\n50% increased Defences from Equipped Shield\n+5% Chance to Block Attack Damage while holding a Shield',
    'Aerialist': '3% chance to Dodge Attack Hits\n3% chance to Dodge Spell Hits\n5% increased Dexterity',
    'Elegant Form': '30% chance to Avoid Elemental Ailments\n3% chance to Dodge Attack Hits\n3% chance to Dodge Spell Hits',
    'Darting Movements': '5% increased Movement Speed\n5% chance to Dodge Attack and Spell Hits while moving',
    'No Witnesses': '10% chance to gain Elusive on Kill\n25% increased Elusive Effect',
    'Molten One\'s Mark': '+2% to maximum Fire Resistance\nRegenerate 1% of Life per second',
    'Fire Attunement': '40% reduced Ignite Duration on you\n50% reduced Extra Damage taken from Critical Strikes while Ignited',
    'Pure Might': '40% increased Stun and Block Recovery\nPurity of Fire has 30% reduced Mana Reservation\n+20 to Strength',
    'Blacksmith': '25% increased Armour\n+20% to Fire Resistance\n0.4% of Fire Damage Leeched as Life',
    'Non-Flammable': '+20% to Fire Resistance\n40% chance to Avoid being Ignited\n6% chance to Avoid Fire Damage from Hits',
    'Winter Prowler': '+2% to maximum Cold Resistance\n6% increased Movement Speed',
    'Hibernator': '40% reduced Freeze Duration on you\n15% additional Physical Damage Reduction while Frozen',
    'Pure Guile': 'Purity of Ice has 30% reduced Mana Reservation\n+20 to Dexterity\n5% chance to Blind Enemies on Hit',
    'Alchemist': '+20% to Cold Resistance\n8% increased Attack and Cast Speed\n20% increased Life Recovery from Flasks',
    'Antifreeze': '+20% to Cold Resistance\n40% chance to Avoid being Frozen\n6% chance to Avoid Cold Damage from Hits',
    'Wizardry': '8% increased maximum Mana\n+2% to maximum Lightning Resistance',
    'Capacitor': '12% increased Movement Speed while Shocked\n40% reduced Effect of Shock on you',
    'Pure Aptitude': 'Regenerate 1% of Energy Shield per second\nPurity of Lightning has 30% reduced Mana Reservation\n+20 to Intelligence',
    'Sage': '20% increased Mana Regeneration Rate\n+20% to Lightning Resistance\nRegenerate 1.5% of Life per second',
    'Insulated': '+20% to Lightning Resistance\n40% chance to Avoid being Shocked\n6% chance to Avoid Lightning Damage from Hits',
    'Born of Chaos': '+3% to maximum Chaos Resistance',
    'Antivenom': '+17% to Chaos Resistance\nUnaffected by Poison',
    'Rot-Resistant': '+13% to Chaos Resistance\nRegenerate 1.2% of Life per second\nRegenerate 0.6% of Energy Shield per second\nRegenerate 0.3% of Mana per second',
    'Blessed': '6% increased maximum Life\n10% increased maximum Mana\n+13% to Chaos Resistance',
    'Student of Decay': '25% increased Damage over Time\n+13% to Chaos Resistance'
  }

  const tradeItemObserver = new MutationObserver(mutations =>
    mutations.forEach(mutation => {
      mutation.addedNodes?.forEach(node => {
        node.querySelectorAll?.('div.explicitMod').forEach(explicitModDiv => {
          const notableName = /1 Added Passive Skill is (.*)/.exec(explicitModDiv.querySelector('span.lc.s')?.textContent)?.[1]
          for (const notableDescriptionLine of notables[notableName]?.split(/\r?\n/) ?? []) {
            const descriptionDiv = document.createElement('div')

            const descriptionSpan = document.createElement('span')
            descriptionSpan.textContent = notableDescriptionLine
            descriptionDiv.appendChild(descriptionSpan)

            explicitModDiv.parentNode?.insertBefore(descriptionDiv, explicitModDiv.nextSibling)
          }
        })
      })
    })
  )
  const addResultSetObserver = resultSetDiv => {
    tradeItemObserver.observe(resultSetDiv, { childList: true })
  }
  const resultSetObserver = new MutationObserver(mutations =>
    mutations.forEach(mutation => {
      mutation.addedNodes?.forEach(node => {
        if (node.classList?.contains('resultset')) {
          addResultSetObserver(node)
        }
      })
    })
  )

  const resultSetDiv = document.querySelector('div.resultset')
  if (resultSetDiv) {
    addResultSetObserver(resultSetDiv)
  } else {
    resultSetObserver.observe(document.documentElement || document.body, { childList: true, subtree: true })
  }
})()
